- name: install apache and php packages for Ubuntu servers
  tags: apache, apache2, ubuntu
  apt:
    name:
      - "{{ apache_package_name }}"
      - "{{ php_package_name }}"
    state: latest

- name: copy default html file for site
  tags: apache, apache2, httpd
  copy: 
    src: files/default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644  


